### ISSUE TITLE
sidecar setup for percona mongodb

### ISSUE THREAD

**Issue by kaykhan** [andrii29/mongodb-profiler-exporter#18]
Can i use this as a sidecar for percona mongodb? e.g How would [mongodb-profiler-exporter](https://github.com/andrii29/mongodb-profiler-exporter) fit into this ?

```
    sidecars:
    - image: percona/mongodb_exporter:0.44
      name: metrics
      env:
      - name: EXPORTER_USER
        valueFrom:
          secretKeyRef:
            name: psmdb-default-sharded-secrets
            key: MONGODB_CLUSTER_MONITOR_USER
      - name: EXPORTER_PASS
        valueFrom:
          secretKeyRef:
            name: psmdb-default-sharded-secrets
            key: MONGODB_CLUSTER_MONITOR_PASSWORD
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: MONGODB_URI
        value: "mongodb://$(EXPORTER_USER):$(EXPORTER_PASS)@$(POD_IP):27017"
      args: ["--discovering-mode", "--compatible-mode", "--collect-all", "--mongodb.uri=$(MONGODB_URI)"]
```

**Comment by andrii29** [comment]
Metric names in `mongodb-profiler-exporter` start with the `slow_queries_` prefix. If there are no metrics with the same names in the Percona exporter, there should be no issues running both exporters simultaneously.

I haven't tested the environment variables like this, but you can start with a similar configuration.

```
      - name: MONGODB_URI
        value: "mongodb://$(EXPORTER_USER):$(EXPORTER_PASS)@$(POD_IP):27017"
```

```
    sidecars:
    - image: percona/mongodb_exporter:0.44
      name: metrics
      env:
      - name: EXPORTER_USER
        valueFrom:
          secretKeyRef:
            name: psmdb-default-sharded-secrets
            key: MONGODB_CLUSTER_MONITOR_USER
      - name: EXPORTER_PASS
        valueFrom:
          secretKeyRef:
            name: psmdb-default-sharded-secrets
            key: MONGODB_CLUSTER_MONITOR_PASSWORD
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: MONGODB_URI
        value: "mongodb://$(EXPORTER_USER):$(EXPORTER_PASS)@$(POD_IP):27017"
      args: ["--discovering-mode", "--compatible-mode", "--collect-all", "--mongodb.uri=$(MONGODB_URI)"]
    - image: andriik/mongodb-profiler-exporter:1.15.1
      name: metrics-profiler
      env:
      - name: EXPORTER_USER
        valueFrom:
          secretKeyRef:
            name: psmdb-default-sharded-secrets
            key: MONGODB_CLUSTER_MONITOR_USER
      - name: EXPORTER_PASS
        valueFrom:
          secretKeyRef:
            name: psmdb-default-sharded-secrets
            key: MONGODB_CLUSTER_MONITOR_PASSWORD
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: MONGODB_URI
        value: "mongodb://$(EXPORTER_USER):$(EXPORTER_PASS)@$(POD_IP):27017"
```
